server.port=8085
spring.application.name=order-service
cropdeal.crop-service.url=http://crop-service:8083
cropdeal.payment-service.url=http://payment-service:8086
cropdeal.wallet-service.url=http://wallet-service:8087